2024-05-31 01:26:32 INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66595f865b496002cc06dffe, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-ykxdvvh-shard-00-00.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-01.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AttributeError('module service_identity has no attribute SICertificateError')>, <ServerDescription ('ac-ykxdvvh-shard-00-02.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66595f865b496002cc06dffe"}, "remainingTimeMS": 29}
2024-05-31 01:26:32 INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66595f865b496002cc06dffe, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-ykxdvvh-shard-00-00.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-01.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AttributeError('module service_identity has no attribute SICertificateError')>, <ServerDescription ('ac-ykxdvvh-shard-00-02.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66595f865b496002cc06dffe"}, "remainingTimeMS": 29}
2024-05-31 02:17:18 INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66596b6cdc3f28e8c9799b66, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-ykxdvvh-shard-00-00.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-01.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-02.cejdegd.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.31696267300000613>]>", "clientId": {"$oid": "66596b6cdc3f28e8c9799b66"}, "remainingTimeMS": 29}
2024-05-31 02:17:18 INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66596b6cdc3f28e8c9799b66, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-ykxdvvh-shard-00-00.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-01.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-02.cejdegd.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.31696267300000613>]>", "clientId": {"$oid": "66596b6cdc3f28e8c9799b66"}, "remainingTimeMS": 29}
2024-05-31 02:24:12 INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66596d0390cd0b9c100fed65, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-ykxdvvh-shard-00-00.cejdegd.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.3089207209999927>, <ServerDescription ('ac-ykxdvvh-shard-00-01.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AttributeError('module service_identity has no attribute SICertificateError')>, <ServerDescription ('ac-ykxdvvh-shard-00-02.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AttributeError('module service_identity has no attribute SICertificateError')>]>", "clientId": {"$oid": "66596d0390cd0b9c100fed65"}, "remainingTimeMS": 29}
2024-05-31 07:44:58 INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 6659b838cbea33d92416aabb, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-ykxdvvh-shard-00-00.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-01.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('ac-ykxdvvh-shard-00-02.cejdegd.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "6659b838cbea33d92416aabb"}, "remainingTimeMS": 29}
2024-05-31 08:38:15 ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-31 08:38:15 ERROR - Exception traceback:
Traceback (most recent call last):
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-05-31 08:41:10 ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-31 08:41:10 ERROR - Exception traceback:
Traceback (most recent call last):
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdul/.local/lib/python3.11/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

